# DataSource Config
spring:
  web:
    resources:
      static-locations:
        - classpath:/statistic/
        - classpath:/Templates/
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
    #设置空如何序列化
    defaultPropertyInclusion: non_null
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3308/water?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

server:
  servlet:
    context-path: /water
    session:
      timeout: 36000
  port: 8080
  tomcat:
    max-http-form-post-size: 104857600
